# typos (spell checker) configuration

[files]
# ignore these files
extend-exclude = ["src/gen/*.rs"]

[default.extend-identifiers]
# overrides: if right side of equals is same as left side, no change is made
